// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microtodo/design
// --out=$(GOPATH)/src/github.com/Microkubes/microtodo
// --version=v1.3.1

package client

import (
	"net/http"
	"time"
)

// TodoMedia media type (default view)
//
// Identifier: application/json; view=default
type TodoMedia struct {
	CreatedAt   *time.Time `form:"created_at,omitempty" json:"created_at,omitempty" xml:"created_at,omitempty"`
	Description *string    `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	ID          *string    `bson:"_id,omitempty" form:"id,omitempty" json:"id,omitempty" yaml:"id,omitempty"`
	Status      *string    `form:"status,omitempty" json:"status,omitempty" xml:"status,omitempty"`
	Title       *string    `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}

// DecodeTodoMedia decodes the TodoMedia instance encoded in resp body.
func (c *Client) DecodeTodoMedia(resp *http.Response) (*TodoMedia, error) {
	var decoded TodoMedia
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// TodoMediaCollection is the media type for an array of TodoMedia (default view)
//
// Identifier: application/json; type=collection; view=default
type TodoMediaCollection []*TodoMedia

// DecodeTodoMediaCollection decodes the TodoMediaCollection instance encoded in resp body.
func (c *Client) DecodeTodoMediaCollection(resp *http.Response) (TodoMediaCollection, error) {
	var decoded TodoMediaCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}
