version: "3.5"
services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tododb

  todo-service:
    build: .
    ports:
      - 8080:8080
    environment:
      TODO_HOST: mongo
      TODO_USERNAME: admin
      TODO_PASSWORD: admin
    restart: always
