consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  FilterTodoPayload:
    example:
      filter: "1971-12-03T04:24:10Z"
      order:
      - direction: Placeat fugiat mollitia reiciendis.
        property: Nostrum accusantium molestias blanditiis nam.
      - direction: Placeat fugiat mollitia reiciendis.
        property: Nostrum accusantium molestias blanditiis nam.
      page: 3.3075532419454213e+18
      pageSize: 2.4332913109882424e+18
    properties:
      filter:
        description: Filter by fields key=>value
        example: "1971-12-03T04:24:10Z"
      order:
        description: Sort specifications.
        example:
        - direction: Placeat fugiat mollitia reiciendis.
          property: Nostrum accusantium molestias blanditiis nam.
        - direction: Placeat fugiat mollitia reiciendis.
          property: Nostrum accusantium molestias blanditiis nam.
        items:
          $ref: '#/definitions/OrderSpecs'
        type: array
      page:
        description: Page number to fetch
        example: 3.3075532419454213e+18
        format: int64
        type: integer
      pageSize:
        description: Number of items per page
        example: 2.4332913109882424e+18
        format: int64
        type: integer
    required:
    - page
    - pageSize
    title: FilterTodoPayload
    type: object
  OrderSpecs:
    example:
      direction: Placeat fugiat mollitia reiciendis.
      property: Nostrum accusantium molestias blanditiis nam.
    properties:
      direction:
        description: Sort direction. One of 'asc' (ascending) or 'desc' (descenting).
        example: Placeat fugiat mollitia reiciendis.
        type: string
      property:
        description: Order by property
        example: Nostrum accusantium molestias blanditiis nam.
        type: string
    title: OrderSpecs
    type: object
  PaginatedTodosMedia:
    description: PaginatedTodosMedia media type (default view)
    example:
      items:
      - completedAt: 1.7849052587171064e+18
        createdAt: 5.1631909098674925e+17
        createdBy: Id dolores ut iusto sit.
        description: Velit sint ipsa.
        done: true
        id: Cumque eum.
        title: Suscipit quibusdam explicabo et.
      - completedAt: 1.7849052587171064e+18
        createdAt: 5.1631909098674925e+17
        createdBy: Id dolores ut iusto sit.
        description: Velit sint ipsa.
        done: true
        id: Cumque eum.
        title: Suscipit quibusdam explicabo et.
      page: 2.882143528128257e+18
      pageSize: 4.978421365317148e+18
      total: 5.106032969635308e+18
    properties:
      items:
        description: List of todos
        example:
        - completedAt: 1.7849052587171064e+18
          createdAt: 5.1631909098674925e+17
          createdBy: Id dolores ut iusto sit.
          description: Velit sint ipsa.
          done: true
          id: Cumque eum.
          title: Suscipit quibusdam explicabo et.
        - completedAt: 1.7849052587171064e+18
          createdAt: 5.1631909098674925e+17
          createdBy: Id dolores ut iusto sit.
          description: Velit sint ipsa.
          done: true
          id: Cumque eum.
          title: Suscipit quibusdam explicabo et.
        items:
          $ref: '#/definitions/TodoMedia'
        type: array
      page:
        description: Current page number
        example: 2.882143528128257e+18
        format: int64
        type: integer
      pageSize:
        description: Number of items per page
        example: 4.978421365317148e+18
        format: int64
        type: integer
      total:
        description: Total number of items
        example: 5.106032969635308e+18
        format: int64
        type: integer
    title: 'Mediatype identifier: paginatedtodosmedia; view=default'
    type: object
  TodoMedia:
    description: TodoMedia media type (default view)
    example:
      completedAt: 1.7849052587171064e+18
      createdAt: 5.1631909098674925e+17
      createdBy: Id dolores ut iusto sit.
      description: Velit sint ipsa.
      done: true
      id: Cumque eum.
      title: Suscipit quibusdam explicabo et.
    properties:
      completedAt:
        example: 1.7849052587171064e+18
        format: int64
        type: integer
      createdAt:
        example: 5.1631909098674925e+17
        format: int64
        type: integer
      createdBy:
        example: Id dolores ut iusto sit.
        type: string
      description:
        example: Velit sint ipsa.
        type: string
      done:
        example: true
        type: boolean
      id:
        example: Cumque eum.
        type: string
      title:
        example: Suscipit quibusdam explicabo et.
        type: string
    required:
    - id
    - createdAt
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  TodoPayload:
    description: Todo payload
    example:
      description: Sed minus.
      title: Et reprehenderit officia aut.
    properties:
      description:
        description: Todo description
        example: Sed minus.
        type: string
      title:
        description: Todo title
        example: Et reprehenderit officia aut.
        type: string
    required:
    - title
    - description
    title: TodoPayload
    type: object
  TodoUpdatePayload:
    description: Todo update payload
    example:
      description: Eum dolores dolore similique soluta officiis.
      done: false
      title: Fuga soluta.
    properties:
      description:
        description: Todo description
        example: Eum dolores dolore similique soluta officiis.
        type: string
      done:
        description: Todo status
        example: false
        type: boolean
      title:
        description: Todo title
        example: Fuga soluta.
        type: string
    title: TodoUpdatePayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  title: Micro Todo
  version: ""
paths:
  /todo/{todoID}:
    get:
      description: Get todo by ID
      operationId: todo#getById
      parameters:
      - description: Todo ID
        in: path
        name: todoID
        required: true
        type: string
      produces:
      - application/json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: getById todo
      tags:
      - todo
    patch:
      description: Update todo
      operationId: todo#updateTodo#1
      parameters:
      - description: Todo ID
        in: path
        name: todoID
        required: true
        type: string
      - description: Todo update payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/TodoUpdatePayload'
      produces:
      - application/json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: updateTodo todo
      tags:
      - todo
    put:
      description: Update todo
      operationId: todo#updateTodo
      parameters:
      - description: Todo ID
        in: path
        name: todoID
        required: true
        type: string
      - description: Todo update payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/TodoUpdatePayload'
      produces:
      - application/json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: updateTodo todo
      tags:
      - todo
  /todo/{todoID}/delete:
    delete:
      description: Delete todo
      operationId: todo#deleteTodo
      parameters:
      - description: Todo ID
        in: path
        name: todoID
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: deleteTodo todo
      tags:
      - todo
  /todo/add:
    post:
      description: Add new todo
      operationId: todo#addTodo
      parameters:
      - description: Todo payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/TodoPayload'
      produces:
      - application/json
      - application/vnd.goa.error
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/TodoMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: addTodo todo
      tags:
      - todo
  /todo/all:
    get:
      description: Get all todos
      operationId: todo#getAllTodos
      parameters:
      - description: Limit todos per page
        in: query
        name: limit
        required: false
        type: integer
      - description: number of todos to skip
        in: query
        name: offset
        required: false
        type: integer
      - description: order by
        in: query
        name: order
        required: false
        type: string
      - enum:
        - asc
        - desc
        in: query
        name: sorting
        required: false
        type: string
      produces:
      - application/vnd.goa.error
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: getAllTodos todo
      tags:
      - todo
  /todo/filter:
    post:
      description: Filter (lookup) todos
      operationId: todo#filterTodos
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/FilterTodoPayload'
      produces:
      - application/vnd.goa.error
      - paginatedtodosmedia
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedTodosMedia'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: filterTodos todo
      tags:
      - todo
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
