consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Todo:
    example:
      completedAt: 1988-05-02T12:20:46Z
      createdAt: 2008-04-25T11:36:34Z
      description: Culpa sed.
      done: false
      id: Et reprehenderit officia aut.
      owner: Dolorum deserunt ad placeat fugiat mollitia reiciendis.
      title: Nostrum accusantium molestias blanditiis nam.
    properties:
      completedAt:
        description: Timestamp (milliseconds) when this todo item was completed.
        example: 1988-05-02T12:20:46Z
        format: date-time
        type: string
      createdAt:
        description: Timestamp (milliseconds) when this todo item was created.
        example: 2008-04-25T11:36:34Z
        format: date-time
        type: string
      description:
        description: Todo item text.
        example: Culpa sed.
        type: string
      done:
        description: Is this todo item completed.
        example: false
        type: boolean
      id:
        description: The item's unique identifier.
        example: Et reprehenderit officia aut.
        type: string
      owner:
        description: Todo item owner's user ID
        example: Dolorum deserunt ad placeat fugiat mollitia reiciendis.
        type: string
      title:
        description: Todo item title.
        example: Nostrum accusantium molestias blanditiis nam.
        type: string
    title: Todo
    type: object
  TodoMedia:
    description: TodoMedia media type (default view)
    example:
      completedAt: 1973-08-12T21:19:28Z
      createdAt: 1971-03-28T22:27:26Z
      description: Id dolores ut iusto sit.
      done: true
      id: Sint ipsa.
      owner: Et cumque eum ut suscipit.
      title: Explicabo et.
    properties:
      completedAt:
        example: 1973-08-12T21:19:28Z
        format: date-time
        type: string
      createdAt:
        example: 1971-03-28T22:27:26Z
        format: date-time
        type: string
      description:
        example: Id dolores ut iusto sit.
        type: string
      done:
        example: true
        type: boolean
      id:
        example: Sint ipsa.
        type: string
      owner:
        example: Et cumque eum ut suscipit.
        type: string
      title:
        example: Explicabo et.
        type: string
    required:
    - id
    - createdAt
    - done
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  TodoMediaCollection:
    description: TodoMediaCollection is the media type for an array of TodoMedia (default
      view)
    example:
    - completedAt: 1973-08-12T21:19:28Z
      createdAt: 1971-03-28T22:27:26Z
      description: Id dolores ut iusto sit.
      done: true
      id: Sint ipsa.
      owner: Et cumque eum ut suscipit.
      title: Explicabo et.
    items:
      $ref: '#/definitions/TodoMedia'
    title: 'Mediatype identifier: application/json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  title: Micro Todo
  version: ""
paths:
  /todo:
    get:
      operationId: todo#list
      produces:
      - application/json; type=collection
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoMediaCollection'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: list todo
      tags:
      - todo
    post:
      operationId: todo#add
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Todo'
      produces:
      - application/vnd.goa.error
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: add todo
      tags:
      - todo
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
