// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microtodo/design
// --out=$(GOPATH)/src/github.com/Microkubes/microtodo
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// TodoController is the controller interface for the Todo actions.
type TodoController interface {
	goa.Muxer
	Add(*AddTodoContext) error
	List(*ListTodoContext) error
}

// MountTodoController "mounts" a Todo resource controller on the given service.
func MountTodoController(service *goa.Service, ctrl TodoController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewAddTodoContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*Todo)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Add(rctx)
	}
	service.Mux.Handle("POST", "/", ctrl.MuxHandler("add", h, unmarshalAddTodoPayload))
	service.LogInfo("mount", "ctrl", "Todo", "action", "Add", "route", "POST /")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListTodoContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.List(rctx)
	}
	service.Mux.Handle("GET", "/", ctrl.MuxHandler("list", h, nil))
	service.LogInfo("mount", "ctrl", "Todo", "action", "List", "route", "GET /")
}

// unmarshalAddTodoPayload unmarshals the request body into the context request data Payload field.
func unmarshalAddTodoPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &todo{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
