// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microtodo/design
// --out=$(GOPATH)/src/github.com/Microkubes/microtodo
// --version=v1.3.1

package app

import (
	"time"
)

// TodoMedia media type (default view)
//
// Identifier: application/json; view=default
type TodoMedia struct {
	CreatedAt   *time.Time `form:"created_at,omitempty" json:"created_at,omitempty" xml:"created_at,omitempty"`
	Description *string    `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	ID          *string    `bson:"_id,omitempty" form:"id,omitempty" json:"id,omitempty" yaml:"id,omitempty"`
	Status      *string    `form:"status,omitempty" json:"status,omitempty" xml:"status,omitempty"`
	Title       *string    `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}

// TodoMediaCollection is the media type for an array of TodoMedia (default view)
//
// Identifier: application/json; type=collection; view=default
type TodoMediaCollection []*TodoMedia
