// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Microkubes/examples/todo/todo-service/design
// --out=$(GOPATH)/src/github.com/Microkubes/examples/todo/todo-service
// --version=v1.3.1

package app
