// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application User Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/examples/todo/todo-service/design
// --out=$(GOPATH)/src/github.com/Microkubes/examples/todo/todo-service
// --version=v1.3.1

package app

import (
	"time"
)

// todo user type.
type todo struct {
	// Timestamp (milliseconds) when this todo item was completed.
	CompletedAt *time.Time `form:"completedAt,omitempty" json:"completedAt,omitempty" xml:"completedAt,omitempty"`
	// Timestamp (milliseconds) when this todo item was created.
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty" xml:"createdAt,omitempty"`
	// Todo item text.
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// Is this todo item completed.
	Done *bool `form:"done,omitempty" json:"done,omitempty" xml:"done,omitempty"`
	// The item's unique identifier.
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Todo item owner's user ID
	Owner *string `form:"owner,omitempty" json:"owner,omitempty" xml:"owner,omitempty"`
	// Todo item title.
	Title *string `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}

// Publicize creates Todo from todo
func (ut *todo) Publicize() *Todo {
	var pub Todo
	if ut.CompletedAt != nil {
		pub.CompletedAt = ut.CompletedAt
	}
	if ut.CreatedAt != nil {
		pub.CreatedAt = ut.CreatedAt
	}
	if ut.Description != nil {
		pub.Description = ut.Description
	}
	if ut.Done != nil {
		pub.Done = ut.Done
	}
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Owner != nil {
		pub.Owner = ut.Owner
	}
	if ut.Title != nil {
		pub.Title = ut.Title
	}
	return &pub
}

// Todo user type.
type Todo struct {
	// Timestamp (milliseconds) when this todo item was completed.
	CompletedAt *time.Time `form:"completedAt,omitempty" json:"completedAt,omitempty" xml:"completedAt,omitempty"`
	// Timestamp (milliseconds) when this todo item was created.
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty" xml:"createdAt,omitempty"`
	// Todo item text.
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// Is this todo item completed.
	Done *bool `form:"done,omitempty" json:"done,omitempty" xml:"done,omitempty"`
	// The item's unique identifier.
	ID *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// Todo item owner's user ID
	Owner *string `form:"owner,omitempty" json:"owner,omitempty" xml:"owner,omitempty"`
	// Todo item title.
	Title *string `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}
