// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "microtodo": Application User Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microtodo/design
// --out=$(GOPATH)/src/github.com/Microkubes/microtodo
// --version=v1.3.1

package client

// todo user type.
type todo struct {
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	Title       *string `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}

// Publicize creates Todo from todo
func (ut *todo) Publicize() *Todo {
	var pub Todo
	if ut.Description != nil {
		pub.Description = ut.Description
	}
	if ut.Title != nil {
		pub.Title = ut.Title
	}
	return &pub
}

// Todo user type.
type Todo struct {
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	Title       *string `form:"title,omitempty" json:"title,omitempty" xml:"title,omitempty"`
}
